### ISSUE TITLE
Ignoring the alpha variable

### ISSUE THREAD

**Issue by HoShilo** [wdweeda/ARIbrain#6]
I have noticed that in version 0.2 which is the latest version on the CRAN the ARI function completly ignores the alpha argument. Insted it computes lower bounderies based on the defult 0.05 alpha even if the user provided difrent one.

So i have updated to the newest version of 0.4 and now the ActiveProp seems to changed based on the provided alpha (lower alpha cause lower ActiveProp as wanted) but the headline of the output still provide information based on the defult of 0.05:

```
> res3_ARI=ARI(Pmap,clusters = clstr3, alpha =0.1 ,mask = mask,Statmap = Zmap)
A hommel object for 268598 hypotheses.
Simes inequality is assumed.
Use p.adjust(), discoveries() or localtest() to access this object.

With 0.95 confidence: at least 2904 discoveries.
347 hypotheses with adjusted p-values below 0.05.
```

**Comment by wdweeda** [comment]
I've fixed that the call to summary(hommel) ignored the alpha argument. The argument was passed correctly to the summary_hommel_roi function.
