### ISSUE TITLE
Could not find function "TDPquery"

### ISSUE THREAD

**Issue by HoShilo** [wdweeda/ARIbrain#9]
Hello,

I've been extensively using the ARI method with the ARIbrain package, following the standard procedure of defining clusters using predetermined thresholds. Recently, I attempted to query clusters by TDPs using the `ARIBrainCluster`. I updated the package following the instructions on the README trough Git-Hub, but I encountered an error while trying to use it:

```R
library(RNifti)
library(ARIbrain)
mask_img <- readNifti("/Users/sh/Documents/PTSD/Hariri_general_mask/GMmask.nii")
mask <- mask_img != 0

domino <- readNifti("/Users/sh/Documents/PTSD/Fixed_second_level_analysis/Domino/Tmaps/reward_z1_sepT2.nii.gz")

Zmap = domino
Zmap[!mask] = 0
Pmap <- (1 - pnorm(Zmap))

my_ARIClass = ARIBrainCluster(Pmap, mask, conn = 18, alpha = 0.05)
# Output: The 0.95 confidence lower bound for the TDP concerning all nodes is 0.004445432 

x = TDPquery(my_ARIClass, 0.006)
# Error: could not find function "TDPquery"
```

Additionally, the `?TDPquery` command does not work. Could you please help me resolve this issue?

Thank you.

**Comment by wdweeda** [comment]
Hello,

The problem seems to be the call to TDPquery, it should be called as TDPQuery (with a capital Q). In the most recent update the help files are now corrected, please update to the latest version from github. Hope this helps!

Regards,

Wouter.
